services:
  app:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      WAKU_PORT: ${APP_PORT:-9100}
      APP_PORT: ${APP_PORT:-9100}
      POSTGRES_HOST: ${POSTGRES_HOST:?POSTGRES_HOST is required}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET:?SESSION_SECRET is required}
      WAKU_PUBLIC_WEB_TITLE: ${WAKU_PUBLIC_WEB_TITLE:-Waku Template}
      NODE_ENV: production
    volumes:
      - uploads:/app/public/uploads

volumes:
  uploads:
