// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

// Construct DATABASE_URL from individual POSTGRES_* env vars when not set,
// matching the docker-compose pattern. This means the Prisma CLI (migrate,
// generate, etc.) works whether you set DATABASE_URL directly or just the
// individual pieces.
const {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_HOST = 'localhost',
  POSTGRES_PORT = '5432',
  POSTGRES_DB,
} = process.env;

if (POSTGRES_USER && POSTGRES_PASSWORD && POSTGRES_DB) {
  process.env.DATABASE_URL = `postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
  },
});
